#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : seqdiag
Version  : 0.9.6
Release  : 14
URL      : https://files.pythonhosted.org/packages/b3/b5/aa0c9513df1898ecb4c3930d53e594b2298b3d5a535898f78c65cc0f45e1/seqdiag-0.9.6.tar.gz
Source0  : https://files.pythonhosted.org/packages/b3/b5/aa0c9513df1898ecb4c3930d53e594b2298b3d5a535898f78c65cc0f45e1/seqdiag-0.9.6.tar.gz
Summary  : seqdiag generates sequence-diagram image from text
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause
Requires: seqdiag-bin = %{version}-%{release}
Requires: seqdiag-license = %{version}-%{release}
Requires: seqdiag-python = %{version}-%{release}
Requires: seqdiag-python3 = %{version}-%{release}
Requires: blockdiag
Requires: docutils
BuildRequires : buildreq-distutils3
BuildRequires : olefile
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
`seqdiag` generate sequence-diagram image file from spec-text file.
.. image:: https://drone.io/bitbucket.org/blockdiag/seqdiag/status.png
:target: https://drone.io/bitbucket.org/blockdiag/seqdiag
:alt: drone.io CI build status

%package bin
Summary: bin components for the seqdiag package.
Group: Binaries
Requires: seqdiag-license = %{version}-%{release}

%description bin
bin components for the seqdiag package.


%package license
Summary: license components for the seqdiag package.
Group: Default

%description license
license components for the seqdiag package.


%package python
Summary: python components for the seqdiag package.
Group: Default
Requires: seqdiag-python3 = %{version}-%{release}

%description python
python components for the seqdiag package.


%package python3
Summary: python3 components for the seqdiag package.
Group: Default
Requires: python3-core

%description python3
python3 components for the seqdiag package.


%prep
%setup -q -n seqdiag-0.9.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1545509292
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test || :
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/seqdiag
cp LICENSE %{buildroot}/usr/share/package-licenses/seqdiag/LICENSE
cp src/seqdiag/tests/VLGothic/LICENSE %{buildroot}/usr/share/package-licenses/seqdiag/src_seqdiag_tests_VLGothic_LICENSE
cp src/seqdiag/tests/VLGothic/LICENSE.en %{buildroot}/usr/share/package-licenses/seqdiag/src_seqdiag_tests_VLGothic_LICENSE.en
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/seqdiag

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/seqdiag/LICENSE
/usr/share/package-licenses/seqdiag/src_seqdiag_tests_VLGothic_LICENSE
/usr/share/package-licenses/seqdiag/src_seqdiag_tests_VLGothic_LICENSE.en

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
